language: php

php:
  - 5.5
  - 5.6

before_install: echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/phpspec/phpspec/bin/phpspec run -v
